#!/usr/bin/env bash

if [ -f "${HOME}/.config/xdebug-wrapper" ]; then
    . "${HOME}/.config/xdebug-wrapper"
fi

PHP_BINARY=${PHP_BINARY:="php"}

if ! [ "${EXTENSION_PATH}" ]; then
    EXTENSION_PATH=$(${PHP_BINARY} -r "echo ini_get('extension_dir');")
fi

XDEBUG_FILE=$(find -L "${EXTENSION_PATH}" -name '*xdebug*' | head)
if ! [ "${XDEBUG_FILE}" ]; then
    echo "Xdebug not found in ${EXTENSION_PATH}"
    exit 1
fi

XDEBUG_IDEKEY=${XDEBUG_IDEKEY:="PHPSTORM"}

$PHP_BINARY -dzend_extension="$XDEBUG_FILE" -dxdebug.idekey="${XDEBUG_IDEKEY}" "$@"
