#!/usr/bin/env bash

if [ -f "${HOME}/.config/xdebug-wrapper" ]; then
    . "${HOME}/.config/xdebug-wrapper"
fi

# Update according to your needs
PHP_BINARY=${PHP_BINARY:="php"}

if ! [ "${EXTENSION_PATH}" ]; then
    EXTENSION_PATH=$(${PHP_BINARY} -i | awk '/^extension_dir => (.*)$/ { print $3 }')
fi

XDEBUG_FILE=$(find -L "${EXTENSION_PATH}" -name '*xdebug*' | head)
if ! [ "${XDEBUG_FILE}" ]; then
    echo "Xdebug not found in ${EXTENSION_PATH}"
    exit 1
fi

XDEBUG_IDEKEY=${XDEBUG_IDEKEY:="PHPSTORM"}

# No need to touch this
$PHP_BINARY -dzend_extension="$XDEBUG_FILE" -dxdebug.idekey="${XDEBUG_IDEKEY}" "$@"
